JiaoZi/Models/Books.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.BookComment = new HashSet<BookComment>();
            this.BookComment1 = new HashSet<BookComment>();
            this.OrderDetails = new HashSet<OrderDetails>();
            this.OrderDetails1 = new HashSet<OrderDetails>();
            this.Cars = new HashSet<Cars>();
        }
    
        public int BookID { get; set; }
        public string BookImage { get; set; }
        public string BookName { get; set; }
        public string BookAuthor { get; set; }
        public Nullable<System.DateTime> IssueTime { get; set; }
        public string Publisher { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Category { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookComment> BookComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookComment> BookComment1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Category Category2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
    }
}

JiaoZi/Models/BooksDetails.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JiaoZi.Models
{
    public class BooksDetails
    {
        public IEnumerable<BookComment> Bc{ get;set;}
        public string Comment_Content { get; set; }
        public Books B { get; set; }
        public BooksDetails(int id)
        {
            
            jiaoziEntities db = new jiaoziEntities();
            Bc = db.BookComment.Where(o => o.BookID == id);
            B= db.Books.Where(b => b.BookID == id).FirstOrDefault();
        }
        
    }
}

JiaoZi/Models/Booksview.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JiaoZi.Models
{
    public class Booksview
    {
        public IEnumerable<Books> Search { get; set; }
    }
}

JiaoZi/Models/Cars.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int CartID { get; set; }
        public int BookID { get; set; }
        public int UserID { get; set; }
        public int Count { get; set; }
        public int flag { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}

JiaoZi/Models/Mallview.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JiaoZi.Models
{
    public class Mallview
    {
        public IEnumerable<Category> Category { get; set; }
        public IEnumerable<Books> CateBooks { get; set; }
        public IEnumerable<Books> CateBooks1 { get; set; }
        public IEnumerable<Books> CateBooks2 { get; set; }
        public IEnumerable<Books> CateBooks3 { get; set; }
        public IEnumerable<Books> CateBooks4 { get; set; }
        public IEnumerable<Books> Search { get; set; }
        public IEnumerable<Books> Hotsale { get; set; }
        public IEnumerable<Books> Onsale { get; set; }
        public IEnumerable<Books> NewBooks { get; set; }
        public IEnumerable<OrderDetails> OrderDetails { get; set; }
        public IEnumerable<Orders> Orders { get; set; }
       
    }


}

JiaoZi/Models/OrderDetails.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int OrderDetailsID { get; set; }
        public int BookID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> UserID { get; set; }
        public int OrderId { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Books Books1 { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Orders Orders1 { get; set; }
        public virtual Users Users { get; set; }
    }
}

JiaoZi/Models/Orders.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.OrderDetails1 = new HashSet<OrderDetails>();
        }
    
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public string Tel { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public System.DateTime Time { get; set; }
        public double total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}

JiaoZi/Controllers/MallController.cs
using JiaoZi.Attributes;
using JiaoZi.Models;
using PagedList;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JiaoZi.Controllers
{
    public class MallController : Controller
    {
        jiaoziEntities db = new jiaoziEntities();
        
        IMall imall;
        public MallController()
        {
            
            imall = new Mall();
        }
        // GET: Mall


        //主页显示
        public ActionResult Index()
        {
            #region
            Models.Mallview viewModel = new Models.Mallview

            {

                Hotsale = imall.GetBooksByAmount(),
                Category = imall.Category(),
                CateBooks = imall.GetBooksByCategory(1),
                CateBooks1 = imall.GetBooksByCategory(2),
                CateBooks2 = imall.GetBooksByCategory(3),
                CateBooks3 = imall.GetBooksByCategory(4),
                CateBooks4 = imall.GetBooksByCategory(5),
                NewBooks = imall.GetBooksByTime(),
                Onsale=imall.GetBooksByPrice(),
            };
            #endregion
            return View(viewModel);
        }
        
        //搜索图书
        [HttpPost]
        public ActionResult Sear()
        {
            string search = Request.Form["search"].ToString();
            var Searchbooks = imall.Search(search);
            if(Searchbooks!=null)
            {
                return PartialView(Searchbooks);
            }
            else                                 
                return HttpNotFound();
        }


        //获取导航条
        public ActionResult Nav()
        {
            var CatagoryName = imall.Category();

            return PartialView(CatagoryName);
        }


        //获取数目
        public ActionResult Num()
        {
            int? UserID = Convert.ToInt32(Session["User_id"]);        
            int sum = 0;
            if (UserID!=null)
            {
                foreach(var i in db.Cars.Where(o=>o.UserID==UserID))
                {
                    sum += Convert.ToInt32(i.Count);
                }
                return Content(sum.ToString());
            }
            else
            return Content(0.ToString());
        }

        //根据ID查某本图书的详情及所有评论
        public ActionResult BooksDetails(int id)
        {
            Session["BookID"] = id;
            var a = db.Books.Where(o => o.BookID == id).FirstOrDefault();
            return View(a);
        }

        //分页显示某类图书
        public ActionResult  BooksType(string CategoryName,string currentFilter, int ? page)
        {
            var books = imall.GetBooks();
            if (CategoryName != null)
            {
                page = 1;
            }
            else
            {
                CategoryName = currentFilter;
            }
            ViewBag.CurrentFilter = CategoryName;
            if (!string.IsNullOrEmpty(CategoryName))
            {
                books = books.Where(x => x.Category == CategoryName);

            }
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            return PartialView(books.ToPagedList(pageNumber, pageSize));
        }

        //显示图书
        public ActionResult BooksShow(string CategoryName)
        {
            var books = imall.GetBooks().Where(x => x.Category == CategoryName);
            return View(books);
        }


        //显示评论
        public ActionResult Comment()
        {
            int id = Convert.ToInt32(Session["BookID"]);
            var comment = db.BookComment.Where(x => x.BookID == id);
            return PartialView(comment);
        }


        //异步评论  代码有待改进 
        [HttpPost]
        [Login]
        public ActionResult Comment(BookComment comment,  int CommentBookID, string Comment_Content)
        {
            #region       
            BooksDetails a = new BooksDetails(CommentBookID);
            int UserID;
            var UserComment = a.Bc;
            ViewBag.Comment = UserComment;          
                UserID = Convert.ToInt32(Session["User_id"]);
                //string textarea = Request["Comment_Content"];
                if (ModelState.IsValid)
                {
                    if (Comment_Content!= "")
                    {
                        comment.UserID = UserID;
                        comment.BookID = CommentBookID;
                        comment.Comment_Content = Comment_Content;
                        comment.Comment_Time = System.DateTime.Now;
                        imall.AddComment(comment);
                        UserComment = a.Bc;
                    ViewBag.Comment = UserComment;                   
                    return PartialView(ViewBag.Comment as IEnumerable<BookComment>);
                   
                }
                    else
                    {                     
                    return PartialView(ViewBag.Comment as IEnumerable<BookComment>);
                }
                }
                    return PartialView(ViewBag.Comment as IEnumerable<BookComment>);
            #endregion

        }

        //评论的实验代码
        #region
        //  [HttpPost]
        //  [Login]
        //  public ActionResult Comment()
        //   {
        //    int BookID = Convert.ToInt32(Request.Form["Comment_BookID"].ToString());
        //    BooksDetails a = new BooksDetails(BookID);
        //    int UserID;
        //    var UserComment = a.Bc;
        //    ViewBag.Comment = UserComment;
        //    if (Session["User_id"]!=null)
        //        {
        //        UserID = Convert.ToInt32(Session["User_id"]);
        //        string textarea = Request["Comment_Content"];
        //        DateTime dateTime = System.DateTime.Now;
        //        if(textarea!=null)
        //        {
        //            imall.bookComments(UserID, BookID, textarea, dateTime);
        //            return PartialView(UserComment);
        //        }
        //        else
        //        {
        //            return Content("<script>alert(评论不能为空')</script>");
        //        }
        //    }
        //    return Content("<script>alert('请先登录');window.location.href='../UserInfo/RegisteLogin';</script>");
        //}
        #endregion

        //显示回复    
        public ActionResult Reply(int id)
        {
            var BooksReply = db.BookRelpy.Where(o => o.BookCommentID == id);        
            return PartialView(BooksReply.ToList());
        }

        [HttpGet]
        public ActionResult ReplyBox()
        {
            return PartialView();
        }

        [HttpPost]
        [Login]
        public JsonResult ReplyBox(int id, string Re_Content, int ReID)
        {
            int UserID = Convert.ToInt32(Session["User_id"]);
            DateTime dateTime = System.DateTime.Now;
            if (Re_Content == "")
            {
                //return Content("<script>alert(评论不能为空')</script>");
                return base.Json("评论不能为空");
            }
            else
                imall.BookReply(id,ReID,dateTime,Re_Content,UserID);
            AjaxMsg msg = new AjaxMsg()
            {
                Mess = "评论成功"
            };
            return base.Json(msg);
        }

        #region
        //[HttpPost]
        //[Login]
        //public JsonResult Reply(int id, string Re_Content, int ReID)
        //{
        //    int UserID = Convert.ToInt32(Session["User_id"]);
        //    DateTime dateTime = System.DateTime.Now;
        //    AjaxMsg msg = new AjaxMsg()
        //    {
        //        Mess = "更改成功"
        //    };
        //    if (Re_Content == "")
        //    {
        //        return base.Json("回复失败");
        //    }
        //    else
        //        imall.BookReply(id, Re_Content, ReID, UserID, dateTime);
        //    //var BooksReply = db.BookRelpy.Where(o => o.BookCommentID == id);
        //    return base.Json(msg);
        //}
        #endregion
        #region
        //[HttpPost]
        //[Login]
        //public ActionResult Reply(int id, string Re_Content, int ReID)
        //{
        //    int UserID = Convert.ToInt32(Session["User_id"]);
        //    DateTime dateTime = System.DateTime.Now;
        //    IEnumerable<BookRelpy> a;
        //    if (Re_Content == "")
        //    {
        //        return Content("<script>alert(评论不能为空')</script>");
        //    }
        //    else
        //    a=  imall.BookReply(id, Re_Content, ReID, UserID, dateTime);
        //    //var BooksReply = db.BookRelpy.Where(o => o.BookCommentID == id);
        //    return PartialView(a);
        //}
        #endregion

        //显示购物车购物车
        public ActionResult Cars()
         {
            var id = Convert.ToInt32(Session["User_id"]);
            var cars = imall.Cars(id);
            return View(cars);
         }

        //加入购物车
        [HttpPost]
        [Login]
        public ActionResult Cars(int BookID)
        {
            int ID = Convert.ToInt32(Session["User_id"]);
            var number = Convert.ToInt32(Request.Form["number"].ToString());
            var count = db.Books.Find(BookID).Amount;
            if (number > count)
            {
                return Content("<script>alert('库存不足，加入失败');history.go(-1);</script>");
            }
            else
            {
                imall.AddBooks(number, BookID, ID);
               
                return Content("<script>alert('加入成功');window.location.href='../Mall/index';</script>");
            }
        }


        //修改数量
        [Login]
        public JsonResult UpdateCar(string  Num,int CarID)
        {
            int num = Convert.ToInt32(Num);
            imall.Update(num, CarID);
            AjaxMsg msg = new AjaxMsg()
            {
                Mess = "更改成功"
            };
            return base.Json(msg);
        }

        //删除某条订单
        [Login]
        public JsonResult DeleteCar(int CarID)
        {
            imall.Delete(CarID);

JiaoZi/Views/Mall/BooksDetails.cshtml
@model JiaoZi.Models.Books
@{
    Layout = "~/Views/Shared/Layoutmall.cshtml";

}
<style>
    * {
        margin: 0;
        padding: 0;
    }
    ul{
        list-style:none;
    }
    .center {
        width: 1005px;
        height: 600px;
        margin-left: 360px;
        margin-top: 20px;
    }

    .pic img {
        width: 300px;
        height: 300px;
    }

    .details {
        width: 300px;
        height: 300px;
        margin-left: 330px;
        margin-top: -300px;

    }
    .comment {
        width: 700px;
        height: 60px;
    }
    .CommentReply{
        width:900px;
        margin:0 auto;
    }
    .CommentReply li{
        margin-bottom:30px;
    }
    .pinglun {
        margin-left: 434px;
        margin-bottom: 40px;
    }
    .textA {
        resize: none;
        border-radius: 4px;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        height: 68px;
        width: 798px;
        display: block;
        border: 1px solid #c03f3c;
    }
    
</style>


<div class="center" id="center">
    <div class="pic">
        <img src="~/@Model.BookImage" />
        <div class="mask"></div>
    </div>

    <div class="details">
        @using (Html.BeginForm("Cars", "Mall"))
        {
        <h3>@Model.BookName</h3>
        <div style="width:100%;height:40px;background-color:lavenderblush;">
            <span style="color:darkgoldenrod;font-size:18px;height:40px;line-height:40px;display:inline-block;" >价格：</span>
            <span style="font-size:24px; color:red">￥@Model.Price</span>
            @Html.Hidden("Price", Model.Price);
        </div>
        <h4 style="color:dimgray">江浙沪顺丰包邮</h4>
        <div style="height:40px;width:100%;margin-top:20px;">
            <span>数量：</span>
            @Html.Hidden("BookID", Model.BookID);
            <input type="number" min="1" max="@Model.Amount" value="1" style="width:80px;" name="number" />         
            <div style="margin-top:10px;">
                <span>库存：</span>
                <span id="kucun">@Model.Amount</span>
                <div style="margin-top:10px;">                  
                    <button style="background-color:red; color:white;" class="btn btn-default" id="jrgwc" type="submit">加入购物车</button>
                    @*<button style="background-color:red; color:white;" class="btn btn-default" id="buy">直接购买</button>*@
                    <button type="button" style="background-color:red; color:white;" class="btn btn-default" data-toggle="modal" data-target="#myModal1" >直接购买</button>
                    <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                                        &times;
                                    </button>
                                    <h4 class="modal-title" id="myModalLabel1">
                                        请填写信息：
                                    </h4>
                                </div>
                                <div class="modal-body">
                                    <label for="Ord_Name">收件人：</label>
                                    <input id="Ord_Name" name="Order_Name" />
                                    <br />
                                    <label for="Ord_Add">地&nbsp;&nbsp;&nbsp;址：</label>
                                    <input id="Ord_Add" name="Order_Add" />
                                    <br />
                                    <label for="Ord_Tel">电&nbsp;&nbsp;&nbsp;话：</label>
                                    <input id="Ord_Tel" name="Order_Tel" />
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">
                                        关闭
                                    </button>
                                    <button type="button" id="Buy" class="btn btn-primary">
                                        提交
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        }
    </div>
</div>
<div class="pinglun"> 
        <textarea id="cc" name="Comment_Content" class="textA"></textarea>
        @Html.Hidden("Comment_BookID", Model.BookID)
        <span><button id="tijiao">提交</button></span>
</div>
<div class="CommentReply" id="CommentReply">
    @Html.Action("Comment","Mall")
    <div class="Reply">
        
    </div>
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    function complete() {
        window.location.reload();
    }
    $(function () {
        var name = $("#Ord_Name");
        var add = $("#Ord_Add");
        var tel = $("#Ord_Tel");
        var total = $("#Price");
        var numb = $("input[name='number']");
        $("#Buy").on("click", function () {
            var BookID = $("#BookID").val();
            $.ajax({
                type: 'Post',
                dataType: 'json',
                url: "/Mall/DirectBuy",
                data: {
                    "BoID": BookID,
                    "Name": name.val(),
                    "Tel": tel.val(),
                    "Add": add.val(),
                    "Total": total.val(),
                    "Num": numb.val(),
                },
                traditional: true,
                success: function (data) {
                    alert(data.Mess);
                    window.history.go(0);
                },
                error: function () {
                    alert("购物失败");
                }
            });
        });
        var text = $("#cc");
        var bookid = $("#BookID");
        $("#tijiao").on("click", function () {
            $.ajax({
                type: 'Post',
                url: "/Mall/Comment",
                data: {
                    "CommentBookID": bookid.val(),
                    "Comment_Content": text.val(),
                },
                success: function (data) {
                    $("#CommentReply").html(data);
                },
                error: function () {
                    alert("评论失败");
                }

            })
        });


        var Re_tishis = $(".Re_tishi");
        for (var i = 0; i < Re_tishis.length; i++) {
            $(Re_tishis[i]).click(function () {
                if ($(this).parent("span").eq(0).next(".Repl_box").css("display") === "none") {
                    $(this).parent("span").eq(0).next(".Repl_box").eq(0).show()
                }
                else
                    $(this).parent("span").eq(0).next(".Repl_box").hide()
            });
        }

        $(".Re_tijiao").each(function () {
            $(this).click(function () {
                var ReID = $(this).parents("dl").eq(0).find("a").eq(0).attr("data-id");
                var BookID = $(this).parents("dl").eq(0).find("a").eq(0).attr("data-Bookid");
                var Rep_Content = $(this).prev();
                $.ajax({
                    type: 'Post',
                    dataType: 'json',
                    url: "/Mall/ReplyBox",
                    traditional: true,
                    data: {
                        "id": BookID,
                        "ReID": ReID,
                        "Re_Content": Rep_Content.val(),
                    },
                    success: function (data) {
                        //$(this).parents(".Reply").eq(0).html(data);
                        alert(data.Mess);
                        window.location.reload();
                    },
                    error: function () {
                        alert("回复失败");
                    }

                })
            })
        })

    })
   

</script>

JiaoZi/Views/Mall/BooksShow.cshtml
@model IEnumerable<JiaoZi.Models.Books>
@{
    Layout = "~/Views/Shared/Layoutmall.cshtml";
}
<div id="DD">
@Html.Action("BooksType", "Mall");
 </div>

JiaoZi/Views/Mall/BooksType.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<JiaoZi.Models.Books>
<style>
    a {
        color: black;
    }

        a:hover {
            text-decoration: none;
        }

    .pic {
        width: 810px;
        height: 600px;
        /*margin:0 auto;*/
        margin-left: 121px;
        float: left;
    }

        .pic img {
            width: 200px;
            height: 200px;
            margin-right: 44px;
        }

    .small {
        width: 200px;
        height: 280px;
        float: left;
    }

        .small .bookpic {
            width: 200px;
            height: 200px;
        }

        .small .bookdetail {
            width: 120px;
            margin: 0 auto;
        }

    .DD {
        margin-top: 20px;
    }

    .page-list ul {
        margin-left: 940px;
        margin-top: -30px;
    }
</style>

<div class="container" style="overflow:hidden" id="con">
    <div class="pic">
        @foreach (var item in Model)
        {
            <div class="small">
                <a href="@Url.Action("BooksDetails", "Mall", new {id=item.BookID})">
                    <div class="bookpic">
                        <img src="~/@item.BookImage" />
                    </div>
                    <div class="bookdetail">
                        <span>￥@item.Price</span>
                        <p>@item.BookName</p>
                    </div>
                </a>
            </div>
        }
    </div>
    <div class="page-list">
        @*<div class="pagecout">Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</div>*@
        @Html.PagedListPager(Model, page => Url.Action("BooksType", "Mall", new { page, currentFilter = ViewBag.CurrentFilter }),
            PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                  new AjaxOptions
                  {
                      HttpMethod = "GET",
                      InsertionMode = InsertionMode.Replace,
                      UpdateTargetId = "DD"
                  }))
        @*@Html.PagedListPager(Model, Page => Url.Action("BooksShow", "Mall", new { Page , currentFilter = ViewBag.CurrentFilter }))*@
    </div>
</div>

JiaoZi/Views/Mall/Comment.cshtml
@model IEnumerable<JiaoZi.Models.BookComment>

<style> 
   
</style>
    <span>全部评论</span>
        <hr />
        <ul>
            @foreach (var i in Model)
            {

            <li>
                <img src="~/@i.Users.HeadImage" class="img-circle" style="width:50px;" />
                <span style="color:orangered">@i.Users.UserName</span>:
                @i.Comment_Content
                <span style="display:inline-block;margin-left:700px;font-size:12px;">@i.Comment_Time <input type="button" value="回复" /></span>
                @*<div class="Com_box">
                    <textarea class="Reply_text"></textarea>
                    <button type="button" class="Re_tijiao">提交</button>
                </div>*@
                <div class="Reply">
                    @*<textarea*@
                    @Html.Action("Reply", "Mall", new { id = i.BookCommentID })
                </div>
            </li>

                }
        </ul>

JiaoZi/Views/Mall/Order.cshtml
@model  IEnumerable<JiaoZi.Models.Orders>

<style>
    .details {
        margin-left: -16px;
        display:none;
    }

    .de th {
       width:300px;
    }
</style>

<div class="container" style="margin:40px auto">
    @{ var num = 0;}
    @foreach (var item in Model)
    {
        num++;
        <div class="row"><span>@num</span>号订单:</div>
        <div class="de">
            <table class="table">
                <tr>
                    <th>
                        收件人
                    </th>
                    <th>
                        总价
                    </th>
                    <th>
                        地址
                    </th>
                    <th></th>
                </tr>
                <tr>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.total
                    </td>
                    <td>
                        @item.Address
                    </td>
                    <td>
                        <button type="button" id="@item.OrderID">查看详情</button>
                        
                    </td>
                </tr>
            </table>
            <div class="details">
                @Html.Action("OrderDetails", "Mall", new { id = item.OrderID })
            </div>
        </div>
    }
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    
    $(function () {
        var buttons = $(":button");
        buttons.each(function () {
            $(this).click(function () {
                if ($(this).parents("table").eq(0).next().css("display") === "none") {
                    $(this).parents("table").eq(0).next().show();
                }
                else
                    $(this).parents("table").eq(0).next().hide();
            })

        })
    })
</script>

JiaoZi/Views/Mall/nav.cshtml
@model  IEnumerable<JiaoZi.Models.Category>



<style>
    .na {
        width: 1759px;
        /*width:1383px;*/
        height: 40px;
        background-color: dimgray;
        text-align: center;
    }

        .na span {
            width: 70px;
            height: 40px;
            line-height: 40px;
            display: inline-block;
            margin-left: 20px;
        }

        .na a {
            text-decoration: none;
            color: aliceblue;
        }

            .na a:hover {
                color: darkred;
            }
</style>



<div class="na"  >
    @*传入name,进入相应视图*@
    <span style="margin-left:-40px;" ><a href="@Url.Action("index","Home")">主页</a></span>
    <span style="background-color:red"><a href="@Url.Action("index","Mall")">首页</a></span>
    @foreach (var item in Model)
    {
        <span>
            <a href="@Url.Action("BooksShow","Mall",new {CategoryName=@item.CategoryName.Trim()})">@item.CategoryName</a>
        </span>
        
    }

</div>