JiaoZi/Models/Shuoshuo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shuoshuo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shuoshuo()
        {
            this.ShuoshuoComment = new HashSet<ShuoshuoComment>();
            this.ShuoshuoComment1 = new HashSet<ShuoshuoComment>();
        }
    
        public int ShuoshuoID { get; set; }
        public string Shuoshuo_Content { get; set; }
        public Nullable<System.DateTime> Shuoshuo_Time { get; set; }
        public Nullable<int> Thumb_Num { get; set; }
        public int UserID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShuoshuoComment> ShuoshuoComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShuoshuoComment> ShuoshuoComment1 { get; set; }
    }
}

JiaoZi/Models/ShuoshuoComment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShuoshuoComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShuoshuoComment()
        {
            this.ShuoshuoComment_Reply = new HashSet<ShuoshuoComment_Reply>();
            this.ShuoshuoComment_Reply1 = new HashSet<ShuoshuoComment_Reply>();
        }
    
        public int ShuoshuoCommentID { get; set; }
        public Nullable<System.DateTime> Comment_Time { get; set; }
        public string Comment_Content { get; set; }
        public int UserID { get; set; }
        public int ShuoshuoID { get; set; }
    
        public virtual Shuoshuo Shuoshuo { get; set; }
        public virtual Shuoshuo Shuoshuo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShuoshuoComment_Reply> ShuoshuoComment_Reply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShuoshuoComment_Reply> ShuoshuoComment_Reply1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}

JiaoZi/Models/ShuoshuoComment_Reply.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShuoshuoComment_Reply
    {
        public int ShuoshuoComment_ReplyID { get; set; }
        public string Reply_Content { get; set; }
        public Nullable<System.DateTime> Reply_Time { get; set; }
        public int UserID { get; set; }
        public int ShuoshuoCommentID { get; set; }
    
        public virtual ShuoshuoComment ShuoshuoComment { get; set; }
        public virtual ShuoshuoComment ShuoshuoComment1 { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}

JiaoZi/Models/Video.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiaoZi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoID { get; set; }
        public string VideoPath { get; set; }
        public Nullable<int> downloadcount { get; set; }
        public Nullable<System.DateTime> Video_Time { get; set; }
        public int UserID { get; set; }
        public string Videoname { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}

JiaoZi/Controllers/KongjianController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JiaoZi.Models;
using System.IO;
using JiaoZi.Attributes;

namespace JiaoZi.Controllers
{
    [Login]
    public class KongjianController : Controller
    {
        Models.jiaoziEntities db = new Models.jiaoziEntities();
        IShuoshuo shuo = new RShuoshuo();
        IText itext = new RText();
        IShuoshuocomment shuocomment = new RShuoshuocomment();
        IVideo ivideo = new RVideo();
        IKongjian ikongjian = new RKongjian();
        Kongjianban kongjianban = new Kongjianban();
        // GET: Kongjian
        public ActionResult Index()
        {
            return View();
        }
        //关注
        public ActionResult guanzhu(int userid1)
        {
            var guanzhuuser = ikongjian.attention(userid1);
            return View(guanzhuuser);
        }
        public ActionResult guanzhu1(int userid1)
        {
            var guanzhuuser = ikongjian.attention(userid1);
            return View(guanzhuuser);
        }
        //粉丝
        public ActionResult fen(int userid1)
        {
            var fens = ikongjian.fens(userid1);
            return View(fens);
        }
        public ActionResult fen1(int userid1)
        {
            var fens = ikongjian.fens(userid1);
            return View(fens);
        }
        /// <summary>
        /// 说说
        /// </summary>
        /// <returns></returns>
        public ActionResult shuoshuo()
        {
            return View();
        }
        //发说说
        [HttpPost]
        public ActionResult shuoshuo(Shuoshuo shuoshuo)
        {
            string shuoshuotextarea = Request["shuoshuoinput"];
            try
            {
                if (ModelState.IsValid)
                {
                    shuoshuo.Shuoshuo_Content = shuoshuotextarea;
                    shuoshuo.Shuoshuo_Time = DateTime.Now;
                    shuoshuo.Thumb_Num = 0;
                    shuoshuo.UserID = Convert.ToInt32(Session["User_id"]);
                    //便于测试
                    //shuoshuo.UserID = 1;
                    shuo.Add(shuoshuo);
                    db.SaveChanges();
                    //return Content("<script>;confirm('发布成功！');window.history.go(0);</script>");
                    return Content("<script>;alert('发布成功！');window.history.go(-1);</script>");
                }
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
            return RedirectToAction("shuoshuo");
        }
        public ActionResult dongtai()
        {
            int id1= Convert.ToInt32(Session["User_id"]);
            var dongtai1 = from s in db.Shuoshuo
                           join a in db.Attention
                           on s.UserID equals a.Attention_UserID
                           where a.UserID ==id1
                           select s;
            return View(dongtai1);
        }
        //列出所有的说说
        public ActionResult allshuoshuo()
        {
            //通过用户id找说说
            var usershuoshuo = shuo.AllShuoByID(Convert.ToInt32(Session["User_id"]));
            //便于测试
            //var usershuoshuo = shuo.AllShuoByID(1);
            //通过说说id找说说评论

            kongjianban.UserAllShuo = usershuoshuo;
            //说说评论
           
            return PartialView(kongjianban);
        }
        //删除说说
        [HttpPost]
        public ActionResult deldeteshuoshuo(int shuoshuoid)
        {
            shuo.delete(shuoshuoid);
            db.SaveChanges();
            //return Content("<script>;alert('删除成功！');window.history.go(-1);</script>");
            return RedirectToAction("shuoshuo");
        }
        //说说评论分部视图
        public ActionResult shuoshuocomment(int shuoshuoid)
        {
            Session["shuoshuoid1"] = shuoshuoid;
            var shuoshuocomment1 = shuocomment.ShuoCommentById(shuoshuoid);
            kongjianban.ShuoCommentById = shuoshuocomment1;
            return PartialView(kongjianban);
        }
        //[HttpPost]
        //public ActionResult shuoshuocomment(ShuoshuoComment comment, int shuoshuoid)
        //{
        //    string commentcontent = Request["commentcontent"];
        //    //ShuoshuoComment comment = new ShuoshuoComment();
        //    try
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            comment.Comment_Content = commentcontent;
        //            comment.Comment_Time = DateTime.Now;
        //            //session代替
        //            comment.UserID = 1;
        //            comment.ShuoshuoID = Convert.ToInt32(Session["shuoshuoid1"]);
        //            shuocomment.addshuocomment(comment);
        //            db.SaveChanges();
        //            return PartialView(kongjianban);
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        return Content(ex.Message);
        //    }
        //    return RedirectToAction("shuoshuocomment");
        //}
        //发表评论
        [HttpPost]
        public ActionResult postshuoshuocomment(int shuoshuoid)
        {
            string commentcontent = Request["commentcontent"];
            ShuoshuoComment comment = new ShuoshuoComment();
            try
            {
                if (ModelState.IsValid)
                {
                    comment.Comment_Content = commentcontent;
                    comment.Comment_Time = DateTime.Now;
                    //session代替
                    comment.UserID = Convert.ToInt32(Session["User_id"]);
                    comment.ShuoshuoID = shuoshuoid;
                    shuocomment.addshuocomment(comment);
                    db.SaveChanges();
                    //return PartialView(kongjianban);
                }
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
            //return Content("<script>alert('关注成功')</script>;window.history.go(-1);");
            return RedirectToAction("shuoshuo");
        }
        //删除评论
        [HttpPost]
        public ActionResult delcomment(int commentid)
        {

            shuocomment.deletecomment(commentid);
            db.SaveChanges();
            return Content("<script>;alert('删除成功！');window.history.go(-1);</script>");
        }
        //用户回复用户评论显示
        public ActionResult shuoshuocommentreply(int commentid)
        {
            var commentreply = ikongjian.allshuoshuocommentreply(commentid);
            return View(commentreply);
        }
        //用户回复用户提交
        [HttpPost]
        public ActionResult postshuoshuocommentreply(ShuoshuoComment_Reply shuocommentreply1,int commentid)
        {
            string commentreplycontent = Request["commentreplycontent"];
            try
            {
                if (ModelState.IsValid)
                {
                    shuocommentreply1.Reply_Content = commentreplycontent;
                    shuocommentreply1.Reply_Time = DateTime.Now;
                    shuocommentreply1.ShuoshuoCommentID = commentid;
                    //后期改成session
                    shuocommentreply1.UserID = Convert.ToInt32(Session["User_id"]);
                    ikongjian.addshuocommentreply(shuocommentreply1);
                    db.SaveChanges();
                    //return PartialView(kongjianban);
                }
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
            //return Content("<script>alert('关注成功')</script>;window.history.go(-1);");
            return RedirectToAction("shuoshuo");
        }

        /// <summary>
        /// 文件
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult File()
        {
            return View();
        }
        //上传文件
        [HttpPost]
        public ActionResult File(HttpPostedFileBase file, Text text)
        {
            //存入项目
            var fileName = file.FileName;
            //string fileName =file.FileName.Replace(Convert.ToChar(DateTime.Now), Convert.ToChar(file.FileName));
            var filePath = Server.MapPath(string.Format("~/{0}", "Text"));
            var newfilePath = Path.Combine(filePath,fileName);
            //相对路径保存至数据库
            var newfilepath = Path.Combine("../Text/", fileName);
            file.SaveAs(newfilePath);
            //保存至数据库
            try
            {
                if (ModelState.IsValid)
                {
                   
                    text.Text_path = newfilepath;
                    text.Text_Time = DateTime.Now;
                    //后期改成 text.UserID = Convert.ToInt32(Session["User_id"]);
                    text.UserID = 1;
                    itext.addtext(text);
                    db.SaveChanges();
                    return PartialView(kongjianban);
                }
            }
            catch (Exception ex)
            {
                return Content(ex.Message);
            }
            return View();
        }
        //查找所有文件
        public ActionResult allfill()
        {
            var useruploadfile = itext.UserUploadText(1);
            kongjianban.userupload = useruploadfile;
            return PartialView(kongjianban);
        }
        /// <summary>
        /// 视频
        /// </summary>
        /// <returns></returns>
        public ActionResult video()
        {
            return View();
        }
        [HttpPost]
        public ActionResult video(HttpPostedFileBase file,Video video)
        {
            //存入项目
            var videoName = file.FileName;
            //string fileName =file.FileName.Replace(Convert.ToChar(DateTime.Now), Convert.ToChar(file.FileName));
            var videoPath = Server.MapPath(string.Format("~/{0}", "Video/"));
            var newvideoPath = Path.Combine(videoPath, videoName);
            file.SaveAs(newvideoPath);
            //保存至数据库
            try
            {

JiaoZi/Views/Kongjian/Index.cshtml
@{
    //ViewBag.Title = "Index";
    Layout = null;
    ViewBag.id = @Session["User_id"];
    ViewBag.img = @Session["User_image"];
    Session["1"] = @Session["User_id"];
    ViewBag.img = @Session["otheruserimg"];
    Session["2"] = @Session["User_image"];
}

        @*@Html.Action("dongtai")

@{
    Layout = null;
}*@

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Layoutkongjian</title>
</head>
<body style="background-color:rgb(238, 235, 235);">
    <style>
        #kongjianbody {
            margin-top: 40px;
        }

        #Mydaohang1 {
            background-color: black;
            border-color: black;
            height: 66px;
        }
    </style>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <link href="~/Content/zui.min.css" rel="stylesheet" />
    <script src="~/Scripts/zui.min.js"></script>
    <link href="~/Content/zui.uploader.min.css" rel="stylesheet" />
    <script src="~/Scripts/zui.uploader.min.js"></script>
    <div class="navbar navbar-inverse navbar-fixed-top" id="Mydaohang1">
        <div class="container-fluid">
            @*<div style="width:50px;height:50px;float:left;margin-left:30px">
                    <img src="@Session["User_image"]" style="width:45px;height:45px;" />
                </div>*@
            <div class="navbar-header" style="margin-left:240px;">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("教资考试服务网", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("考试中心", "KSZX", "Home")</li>*@
                    <li>@Html.ActionLink("教资资讯", "Index", "News")</li>
                    <li>@Html.ActionLink("个人空间", "Index", "Kongjian")</li>
                    <li>@Html.ActionLink("备考资源库", "Index", "Resouce")</li>
                    <li>@Html.ActionLink("考试论坛", "Index", "Luntan")</li>
                    <li>@Html.ActionLink("备考书店", "Index", "Mall")</li>
                </ul>
            </div>
        </div>
    </div>
    <div style="height:80px;width:100%;background-color:#f4511e">
        <span>当前所在页</span>
    </div>
    <div class="container">
        <div class="row" style="background-color:white">
            <div class="col-md-8" style="padding-right:0px;">
               @Html.Action("dongtai")
            </div>
            <div class="col-md-4" style="height:inherit;padding-left:0px;">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            导航
                        </h3>
                        <ul class="nav nav-tabs" id="tabNav" style="font-size:larger">
                            <li>@Html.ActionLink("动态", "Index", "Kongjian")</li>
                            <li>@Html.ActionLink("文件", "File", "Kongjian")</li>
                            <li>@Html.ActionLink("视频", "video", "Kongjian")</li>
                            <li>@Html.ActionLink("说说", "shuoshuo", "Kongjian")</li>
                        </ul>
                        <div style="height:150px">
                            <img src="@Session["User_image"]" style="height:70px;width:70px;border:5px ridge white" />

                        </div>
                        <div class="row" style="height:100px;font-size:large;color:black">
                            <div class="col-md-4">

                                <img src="~/images/icon/icon/love.ico" style="height:10px;width:10px;" />
                                <a href="@Url.Action("guanzhu", "Kongjian", new {userid1=Convert.ToInt32(Session["User_id"]), @style = "color:black;font-size:larger" })" target="_blank">
                                    关注
                                </a>
                            </div>
                            <div class="col-md-4">
                                <img src="~/images/icon/icon/love.ico" style="height:10px;width:10px;" />
                                <a href="@Url.Action("fen", "Kongjian", new {userid1= Convert.ToInt32(Session["User_id"]), @style = "color:black;font-size:larger" })" target="_blank">
                                    粉丝
                                </a>
                            </div>
                            <div class="col-md-4">动态</div>
                        </div>
                    </div>
                    <div class="panel-body">
                        <span>用户推荐</span>
                        <hr />
                        <p>
                            01
                            <a href="@Url.Action("otheruserkongjian", "Kongjian", new { otheruserid = 8})" target="_blank">
                                <img src="~/images/User_HeadImage/8.jpg" style="height:50px;width: 50px;margin-left: 10px;" />
                            </a>
                            <span>老胡</span>
                            <span>
                                @using (Html.BeginForm("UAttentionU", "Kongjian", new { user2id = 8 }, FormMethod.Post))
                                {
                                    <input type="submit" value="关注" />
                                }
                            </span>
                        </p>
                        <p>
                            02
                            <a href="@Url.Action("otheruserkongjian", "Kongjian", new { otheruserid =7})" target="_blank">
                                <img src="~/images/User_HeadImage/7.jpg" style="height: 50px;width: 50px;margin-left: 10px;" />
                            </a>

                            <span>李易峰</span>
                            <span>
                                @using (Html.BeginForm("UAttentionU", "Kongjian", new { user2id = 7 }, FormMethod.Post))
                                {
                                    <input type="submit" value="关注" />
                                }
                            </span>
                        </p>
                        <p>
                            03
                            <a href="@Url.Action("otheruserkongjian", "Kongjian", new { otheruserid =6})" target="_blank">
                                <img src="~/images/User_HeadImage/6.jpg" style="height: 50px;width: 50px;margin-left: 10px;" />
                            </a>

                            <span>小白</span>
                            <span>
                                @using (Html.BeginForm("UAttentionU", "Kongjian", new { user2id = 6 }, FormMethod.Post))
                                {
                                    <input type="submit" value="关注" />
                                }
                            </span>
                        </p>
                        <p>
                            04
                            <a href="@Url.Action("otheruserkongjian", "Kongjian", new { otheruserid =23})" target="_blank">
                                <img src="~/images/User_HeadImage/12.jpg" style="height: 50px;width: 50px;margin-left: 10px;" />
                            </a>

                            <span>赵丽颖</span>
                            <span>
                                @using (Html.BeginForm("UAttentionU", "Kongjian", new { user2id = 23 }, FormMethod.Post))
                                {
                                    <input type="submit" value="关注" />
                                }
                            </span>
                        </p>
                        <span>可能认识的人</span>
                        <hr />
                        <div>
                            <p>
                                01
                                <a href="@Url.Action("otheruserkongjian", "Kongjian", new { otheruserid =24})" target="_blank">
                                    <img src="~/images/User_HeadImage/13.jpg" style="height: 50px;width: 50px;margin-left: 10px;" />
                                </a>

                                <span>林更新</span>
                                <span>
                                    @using (Html.BeginForm("UAttentionU", "Kongjian", new { user2id = 24 }, FormMethod.Post))
                                    {
                                        <input type="submit" value="关注" />
                                    }
                                </span>
                            </p>
                            <p>
                                02
                                <a href="@Url.Action("otheruserkongjian", "Kongjian", new { otheruserid =14})" target="_blank">
                                    <img src="~/images/User_HeadImage/14.jpg" style="height: 50px;width: 50px;margin-left: 10px;" />
                                </a>

                                <span>余淮</span>
                                <span>
                                    @using (Html.BeginForm("UAttentionU", "Kongjian", new { user2id = 14 }, FormMethod.Post))
                                    {
                                        <input type="submit" value="关注" />
                                    }
                                </span>
                            </p>
                            <p>
                                03
                                <a href="@Url.Action("otheruserkongjian", "Kongjian", new { otheruserid =15})" target="_blank">
                                    <img src="~/images/User_HeadImage/15.jpg" style="height: 50px;width: 50px;margin-left: 10px;" />
                                </a>

                                <span>耿耿</span>
                                <span>
                                    @using (Html.BeginForm("UAttentionU", "Kongjian", new { user2id = 15 }, FormMethod.Post))
                                    {
                                        <input type="submit" value="关注" />
                                    }
                                </span>
                            </p>
                            <p>
                                04
                                <a href="@Url.Action("otheruserkongjian", "Kongjian", new { otheruserid =20})" target="_blank">
                                    <img src="~/images/User_HeadImage/16.jpg" style="height: 50px;width: 50px;margin-left: 10px;" />
                                </a>
                                <span>赵又廷</span>
                                <span>
                                    @using (Html.BeginForm("UAttentionU", "Kongjian", new { user2id = 20 }, FormMethod.Post))
                                    {
                                        <input type="submit" value="关注" />
                                    }
                                </span>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

JiaoZi/Views/Kongjian/allfill.cshtml
@model JiaoZi.Models.Kongjianban
@*存在问题*@
<div class="list-group">
    @foreach (var item in Model.userupload)
    {
        <a href="#" class="list-group-item">
            @Html.DisplayFor(modelItem => item.Text_path)
            @item.Text_Time
            @item.TextID
        </a>
        <a href="@item.Text_path">下载</a>
    }
</div>

JiaoZi/Views/Kongjian/allshuoshuo.cshtml
 <!--说说动态-->
@model JiaoZi.Models.Kongjianban
@{
        Layout = null;
     } 
<div class="panel panel-default">
    @foreach (var item in Model.UserAllShuo)
    {
        <div class="panel-title">
            <!--删除 转发 举报-->
            <div class="dropdown">
                <div class="dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-chevron-down"></span>
                </div>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                    <li role="presentation">
                        @using (Html.BeginForm("deldeteshuoshuo", "Kongjian", new { shuoshuoid = @item.ShuoshuoID }, FormMethod.Post))
                        {
                            <input type="submit" value="删除" style="height:32px;width:160px;" class="btn btn-default" />
                        }
                    </li>
                    <li role="presentation">
                        <button style="height:32px;width:160px;" class="btn btn-default">收藏</button>
                    </li>
                    <li role="presentation">
                        <button style="height:32px;width:160px;" class="btn btn-default">举报</button>

                    </li>
                </ul>
            </div>
            <!--/删除 转发 举报-->

        </div>

        <div class="panel-body">
            <div class="row" style="margin:50px;height:auto ">
                <!-- 左-->
                <div class="col-md-2" style="height:400px;">
                    <!-- 头像 -->
                    <div style="height:20%;text-align:right">

                        <img src="@item.Users.HeadImage" style="height:70px;width:70px;border:5px groove white" />
                    </div>
                    <!-- 留白 -->
                    <div style="height:80%"></div>
                </div>
                <!--中-->
                <div class="col-md-8 row" style="height:auto;">
                    <!--边框左-->
                    <div class="col-md-1" style="height:100%;" id="jiantou">
                        <div style="height:100%">

                        </div>
                        <!-- 留白 -->
                        <div style="height:80%"></div>
                    </div>
                    <!--中间右边-->
                    <div class="col-md-10" id="shuocontent">
                        <!--边框上-->
                        <div style="height: 15%; width: 100%;">
                        </div>
                        <!-- 网名 -->
                        <div style="height:15%;width:100%;"></div>
                        <!-- 内容 -->
                        <div style="height:200px;width:100%;overflow-y:auto;">
                            <h4>
                                @item.Users.UserName
                                @item.Shuoshuo_Content
                            </h4>
                            <p> @item.Shuoshuo_Time </p>
                        </div>
                        <p>   
                                 <span class="glyphicon glyphicon-comment"data-toggle="collapse" data-target="#@item.ShuoshuoID">(8)</span>
                                 <span class="glyphicon glyphicon-thumbs-up">(10)</span>
                                 <span class="glyphicon glyphicon-share-alt">(1)</span>
                        </p>
                        <div id="@item.ShuoshuoID" class="collapse">
                            <!-- 点赞、评论、时间 -->
                            <div style="width:100%">
                                @using (Html.BeginForm("postshuoshuocomment", "Kongjian", new { shuoshuoid = @item.ShuoshuoID }, FormMethod.Post))
                                {
                                    <div>
                                        @Html.TextArea("commentcontent", new { placeholder = "输入文字" })
                                        <input type="submit" value="确定" />
                                    </div>
                                }
                                @{Html.RenderAction("shuoshuocomment", "Kongjian", new { shuoshuoid = @item.ShuoshuoID });
                                }
                            </div>
                        </div>
                        <hr />
                    </div>
                </div>
                <!-- 右 -->
                <div class="col-md-2" style="height:400px;">
                    <div style="height:20%"></div>
                    <div style="height:80%"></div>
                </div>
            </div>
            <hr />
        </div>
            }
</div>


       
<!--评论-->
@*<div class="col-md-8" style="height:200px;">
    @foreach (var com in Model.ShuoCommentById)
    {

        @com.ShuoshuoCommentID
        @com.Comment_Content
    }
</div>*@