JiaoZi/Controllers/ResouceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JiaoZi.Models;

namespace JiaoZi.Controllers
{
    public class ResouceController : Controller
    {
        Models.jiaoziEntities db = new Models.jiaoziEntities();
        IResource iresource = new RResource();
        ResourceViewModel resourceviewmodel = new ResourceViewModel();
        // GET: Resouce
        public ActionResult Index()
        {
            resourceviewmodel.alltextresource = iresource.alltextresource();
            resourceviewmodel.allvideoresource = iresource.allvideoresource();
            resourceviewmodel.youertextresource = iresource.TextResourceByStage("幼儿");
            resourceviewmodel.youervideoresource = iresource.VideoResourceByStage("幼儿");
            resourceviewmodel.xiaoxuetextresource = iresource.TextResourceByStage("小学");
            resourceviewmodel.xiaoxuevideoresource = iresource.VideoResourceByStage("小学");
            resourceviewmodel.chuzhongtextresource = iresource.TextResourceByStage("初中");
            resourceviewmodel.chuzhongvideoresource = iresource.VideoResourceByStage("初中");
            resourceviewmodel.gaozhongtextresource = iresource.TextResourceByStage("高中");
            resourceviewmodel.gaozhongvideoresource = iresource.VideoResourceByStage("高中");
            return View(resourceviewmodel);
        }
        public ActionResult allresource()
        {
            resourceviewmodel.alltextresource = iresource.alltextresource();
            resourceviewmodel.allvideoresource = iresource.allvideoresource();
            resourceviewmodel.youertextresource = iresource.TextResourceByStage("幼儿");
            resourceviewmodel.youervideoresource = iresource.VideoResourceByStage("幼儿");
            resourceviewmodel.xiaoxuetextresource = iresource.TextResourceByStage("小学");
            resourceviewmodel.xiaoxuevideoresource = iresource.VideoResourceByStage("小学");
            resourceviewmodel.chuzhongtextresource = iresource.TextResourceByStage("初中");
            resourceviewmodel.chuzhongvideoresource = iresource.VideoResourceByStage("初中");
            resourceviewmodel.gaozhongtextresource = iresource.TextResourceByStage("高中");
            resourceviewmodel.gaozhongvideoresource = iresource.VideoResourceByStage("高中");
            return View(resourceviewmodel);
        }
        public ActionResult videoresouce()
        {
            return View();
        }
        public ActionResult fileresouce()
        {
            var allresource = iresource.alltextresource();
            return View(allresource);
        }
        //搜索资源
        public ActionResult searchresouce()
        {
            string searchString1 = Request["searchString"];
            var text= iresource.searchtextresource(searchString1);
            var video= iresource.searchvideoresource(searchString1);
            resourceviewmodel.searchtextresource = text;
            resourceviewmodel.searchvideoresource = video;
            if (text.FirstOrDefault()== null && video.FirstOrDefault() == null)
            {
                return Content("<script>;alert('不好意思没找到您要的资源');window.history.go(-1);</script>");
                //return Content("不好意思没找到您要的资源");
            }
            //return View("searchresouce");
            else return View(resourceviewmodel);

        }
    }
}

JiaoZi/Views/Resouce/fileresouce.cshtml
@model IEnumerable<JiaoZi.Models.TextResource>
@{ 
    Layout = null;
}

<div class="row">
  
        @foreach (var item in Model)
        {  <div class="col-md-2">
        <img src="~/images/icon/icon/文档.ico" />
        @item.Text_Name
        @item.Text_Time
        <a href="@item.Text">下载</a>
       </div>
        }
  
</div>

JiaoZi/Views/Resouce/searchresouce.cshtml
@model JiaoZi.Models.ResourceViewModel
@{
    Layout = "~/Views/Shared/Layoutkongjian2.cshtml";
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
    <div class="row">
        <div class="col-md-2" style="height:800px;">
            <div class="panel panel-primary" style="width:200px;height:40%;border:1px solid dimgrey">
                <div class="panel-heading" style="background-color:dimgrey">联系我</div>
                <div class="panel-body">
                    <div class="form-horizontal">
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="inputemail">电子邮箱</label>
                            <div class="col-sm-8">
                                <input id="inputemail" type="email" class="form-control" placeholder="email" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label" for="inputname">姓名</label>
                            <div class="col-sm-8">
                                <input id="inputname" type="email" class="form-control" placeholder="name" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-4 col-sm-8">
                                <button type="submit" class="btn btn-default pull-right">
                                    发送
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="myTabContent" class="tab-content col-md-10" style="height:650px;overflow-y:scroll">
            <hr>
            <div>
                <span>你当前的位置</span>
                <b>></b>
                <a href="/Home/Index">教资考试服务网</a>
                <b>></b>
                <a href="/Resouce/Index">备考资源库</a>
                <b>></b>
                <a class="active-tab"><span>搜索</span></a>
                @using (Html.BeginForm("searchresouce", "Resouce"))
                {
                    @Html.TextArea("searchString")
                    <div>
                        <input type="submit" value="搜索" />
                    </div>
                }
            </div>
            @*<p class="active-tab"><strong>你当前的位置</strong>：<span></span></p>*@
            <hr>
            <div class="tab-pane fade in active" id="all">
                <table class="table table-bordered  table-striped ">
                    

                        <tbody id="3tbody">
                            <tr>
                                <td>名称</td>
                                <td>时间</td>
                                <td></td>
                            </tr>
                            @foreach (var item in Model.searchtextresource)
                            {
                                <tr>
                                    <td>
                                        @item.Text_Name
                                    </td>
                                    <td>
                                        @item.Text_Time
                                    </td>
                                    <td>
                                        <a href="@item.Text">下载</a>
                                    </td>
                                </tr>
                            }


                        </tbody>
                    </table>
                   @foreach (var item in Model.searchvideoresource)
                   {
                    @item.Video_Name
                   }
                <br />
                <hr />            
                @*@Html.Action("allresource")*@
            </div>
        </div>
        <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">教资考试服务网</a>
                </div>
            </div>
        </nav>
    </div>
    <script>
    $(function(){
        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            // 获取已激活的标签页的名称
            var activeTab = $(e.target).text();
            // 获取前一个激活的标签页的名称
            var previousTab = $(e.relatedTarget).text();
            $(".active-tab span").html(activeTab);
            $(".previous-tab span").html(previousTab);
        });
    });
    </script>

JiaoZi/Views/Resouce/videoresouce.cshtml
@{
    Layout = null;
}