JiaoZi/Models/Jz/UserInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JiaoZi.Models
{
    public class UserInfo:IUserInfo
    {
        public bool Login(int? UserID, string PasswordL)
        {

            using (jiaoziEntities db=new jiaoziEntities())
            {
                var users = db.Users.Where(x => x.UserID == UserID && x.Password == PasswordL).FirstOrDefault();
                if (users != null)
                {
                    return true;
                }
                else
                    return false;
            }
        }



        public bool Registe(string TrueName, string PasswordR, string Email)
        {
            using (jiaoziEntities db = new jiaoziEntities())
            {

                if (db.Users.Any(x => x.Email == Email))
                {
                    return false;
                }
                else
                {
                    var users = new Users()
                    {
                        TrueName = TrueName,

                        Password = PasswordR,
                        Email = Email
                    };
                    db.Users.Add(users);
                    db.SaveChanges();
                    return true;
                }
            }
        }


        public string FindPassword(string Email, string TrueName)
        {
            using (jiaoziEntities db = new jiaoziEntities())
            {
                var passwords = db.Users.Where(m => m.Email == Email && m.TrueName == TrueName).FirstOrDefault();
                if (passwords != null)
                {
                    var password = passwords.Password;
                    return password;
                }
                else
                {
                    string message = "提交信息有误，找回密码失败！";
                    return message;
                }
            }
        }
    }
}

JiaoZi/Models/RegisteLogin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JiaoZi.Models
{
    public class RegisteLogin
    {
        public int UserID { get; set; }

        [Required]
        [Display(Name = "姓名")]
        public string TrueName { get; set; }

        [Required]
        [Display(Name = "密码")]
        public string PasswordL { get; set; }


        [Required]
        [Display(Name = "密码")]
        [StringLength(20, MinimumLength = 6)]
        public string PasswordR { get; set; }


        [Required]
        [Display(Name = "确认密码")]
        [Compare("PasswordR")]
        public string ConfirmPassword { get; set; }

        [Required]
        [Display(Name = "邮箱")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9._]+\.[A-Za-z]{2,4}")]
        public string Email { get; set; }


        [Display(Name = "记住我")]
        public bool Rememberme { get; set; }

        [Display(Name = "验证码")]
        public string YZM { get; set; }
    }
}

JiaoZi/Controllers/UserInfoController.cs
using JiaoZi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JiaoZi.Controllers
{
    public class UserInfoController : Controller
    {
        jiaoziEntities db = new jiaoziEntities();
        IUserInfo iuser;
        public UserInfoController()
        {
            iuser = new UserInfo();                     //子类以父类的方式出现 ，多态
        }


        //首页
        public ActionResult Index()
        {
            return View();
        }

        //获取验证码
        public ActionResult GetImg()
        {
            int width = 100;
            int height = 40;
            int fontsize = 20;
            string code = string.Empty;
            byte[] bytes = Verify.CreateValidateGraphic(out code, 4, width, height, fontsize);
            Session["YZM"] = code;
            return File(bytes, @"image/jpeg");
        }


        //检查验证码
        public bool CheckYZM(string num)
        {
            string cnum = Session["YZM"] == null ? "" : Session["YZM"].ToString();

            if (num.ToLower() == cnum.ToLower() && !string.IsNullOrEmpty(num))
            {
                return true;
            }
            else
            {
                return false;
            }
        }


        // 登录
        //public ActionResult Login()
        //{
        //    return View();
        //}

        //登录注册
        public ActionResult RegisteLogin()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Registe(string TrueName, string PasswordR, string Email)
        {
            var c = iuser.Registe(TrueName, PasswordR, Email);
            if (c)
            {
                var id = db.Users.Where(m => m.Email == Email).FirstOrDefault().UserID;
                return Content("<script>alert('注册成功！请记住您的ID：" + id + "');window.location.href='../Default/RegisteLogin';</script>");
            }
            return Content("<script>alert('您的邮箱已被注册！请重试');history.go(-1);</script>");
        }



        [HttpPost]
        public ActionResult RegisteLogin(int? UserID, string PasswordL, string YZM)
        {
            string data;
            var url = Request.UrlReferrer;
            var a = iuser.Login(UserID, PasswordL);
            var b = CheckYZM(YZM);
            if (a && !b)
            {
                data = "验证码输入错误，请重试";
                return Content(data);
            }
            else if (a && b)
            {

                Session["User_id"] = UserID;
                Session["User_image"] = db.Users.Where(m => m.UserID == UserID).FirstOrDefault().HeadImage;
                Session["User_Name"] = db.Users.Where(m => m.UserID == UserID).FirstOrDefault().UserName;
                data = "登录成功";
                return Content(data);

            }
            else if (!a && b)
            {
                data = "账号或密码错误，请重试";
                return Content(data);
            }
            else
                data = "请按照格式输入";
            return Content(data);
        }



        //找回密码
        public ActionResult FindPassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FindPassword(string Email, string TrueName)
        {
            string password = iuser.FindPassword(Email, TrueName);
            return Content("<script>alert('" + password + "');window.location.href='../UserInfo/FindPassword';</script>");

        }




        //退出时头像（视图）的变化 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TX()
        {
            //try
            //{
            Session.Abandon();
            Session["User_id"] = null;
            Session["User_image"] = null;
            Session.Remove("User_id");
            return PartialView();
            //return RedirectToAction("page", "Home");
        }
    }
}

JiaoZi/Views/UserInfo/FindPassword.cshtml
@model JiaoZi.Models.RegisteLogin

@{
    ViewBag.Title = "FindPassword";
}

<h2>找回密码</h2>

@using (Html.BeginForm())
{
    <p>
        @Html.LabelFor(m => m.TrueName) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        @Html.TextBoxFor(m => m.TrueName)<br />
        @Html.ValidationMessageFor(m => m.TrueName)
    </p>
    <p>
        @Html.LabelFor(m => m.Email)  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        @Html.TextBoxFor(m => m.Email)<br />
        @Html.ValidationMessageFor(m => m.Email)
    </p>
    <input type="submit" value="确定" />
}

JiaoZi/Views/UserInfo/GetImg.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div class="yzm">
        @using (Ajax.BeginForm("GetImg", "UserInfo", new AjaxOptions()
        {
            HttpMethod = "Post",
            UpdateTargetId = "GM",
            InsertionMode = InsertionMode.Replace
        }))
        {
            <img id="GL_StandardCode" style="cursor: pointer;" src="@Url.Action("GetImg", "UserInfo")?t=@DateTime.Now.Ticks" title="看不清，点击换一张" />
            <button id="GG">换一张</button>
        }
    </div>

</body>
</html>
<script>
    @*$(function () {
        $("#GG").click(function () {
            alert("hello");
             $("#GM").src="@Url.Action("GetImg", "Default")" + "?t=" + (new Date()).getTime();
        })
    })*@
    @*function mm() {
      alert("hello");
      $("#GM").src="@Url.Action("GetImg", "Default")" + "?t=" + (new Date()).getTime();
    }*@
</script>

JiaoZi/Views/UserInfo/RegisteLogin.cshtml
@model JiaoZi.Models.RegisteLogin

@{
    ViewBag.Title = "RegisteLogin";
}
<style type="text/css">
    .box1 {
        width: 410px;
        height: 350px;
        border: 1px solid #dddddd;
        margin: 110px auto;
    }

    .tab-content p {
        margin-top: 20px;
    }

    #GM {
        width: 100px;
        height: 40px;
    }
</style>
<h2 style="text-align:center;color:palevioletred">教资服务网欢迎您</h2>

<div class="box1" style="text-align:center">
    <ul id="myTab" class="nav nav-tabs">
        <li class="active">
            <a href="#home" data-toggle="tab">登录</a>
        </li>
        <li>
            <a href="#re" data-toggle="tab">注册</a>
        </li>
    </ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade in active" id="home">
            @using (Ajax.BeginForm("RegisteLogin", "UserInfo", new AjaxOptions()
            {
                HttpMethod = "Post",
                OnSuccess = "Success",
               
            }
            ))
            {
                <p>
                    ID:&nbsp;&nbsp;&nbsp;

                    @Html.TextBoxFor(m => m.UserID) <br />
                    @Html.ValidationMessageFor(m => m.UserID)
                </p>
                <p>
                    密码:
                    @Html.PasswordFor(m => m.PasswordL)<br />
                    @Html.ValidationMessageFor(m => m.PasswordL)
                </p>
                <p>
                    @Html.LabelFor(m => m.YZM)
                    @Html.TextBoxFor(m => m.YZM)<br />
                    <img id="GM" style="cursor: pointer;" src="~/UserInfo/GetImg" title="看不清，点击换一张" />
                    <button type="button" id="GG">换一张</button>
                </p>
                <p>
                    <input type="submit" value="登录" style="width:80%;background-color:deepskyblue" />
                </p>
                <a href="@Url.Action("FindPassword", "UserInfo")"><span>忘记密码</span></a>
            }
        </div>

        <div class="tab-pane fade" id="re">
            @using (Html.BeginForm("Registe", "UserInfo"))
            {
                <p>
                    @Html.LabelFor(m => m.TrueName) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.TextBoxFor(m => m.TrueName)<br />
                    @Html.ValidationMessageFor(m => m.TrueName)
                </p>
                <p>
                    @Html.LabelFor(m => m.PasswordR) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.PasswordFor(m => m.PasswordR)<br />
                    @Html.ValidationMessageFor(m => m.PasswordR)
                </p>
                <p>
                    @Html.LabelFor(m => m.ConfirmPassword)
                    @Html.PasswordFor(m => m.ConfirmPassword)<br />
                    @Html.ValidationMessageFor(m => m.ConfirmPassword)
                </p>
                <p>
                    @Html.LabelFor(m => m.Email)  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    @Html.TextBoxFor(m => m.Email)<br />
                    @Html.ValidationMessageFor(m => m.Email)
                </p>
                <p>
                    <input type="submit" value="注册" />
                </p>
            }
        </div>

    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
@*<script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>*@
<script type="text/javascript">
    $(function () {
        $("#GG").click(function () {
            $("#GM").attr("src", "/UserInfo/GetImg?t=" + Math.random());
        });
    })
    function Success(e) {
        alert(e);
        if (e == "登录成功") {
            window.window.location.href = document.referrer;           
        }
    }
 
</script>